### ISSUE TITLE
Loading Model for nuclei error 

### ISSUE THREAD

**Issue by DigeSegun** [berylliumsec/nebula#33]
When I run the Nebula command It takes a long time to load the model for nuclei and it kills the program. Sometimes my device freezes at this step. 

Log 
digesegun@digesegun-desktop:~/Desktop/Nebula$ nebula
Running as PYPI package, setting appropriate paths
./unified_models already exists and is not empty.
Loading tokenizer for zap... Done!
Loading model for zap... Done!
Loading tokenizer for crackmap... Done!
Loading model for crackmap... Done!
Loading tokenizer for nuclei... Done!
Loading model for nuclei...Killed

**Comment by berryliumsec** [comment]
@DigeSegun please refer to the system requirements in the Readme. It seems like your system may not have enough memory. We will consider an update to load only the necessary models in future releases to reduce the amount of memory used by Nebula

**Comment by berryliumsec** [comment]
@DigeSegun support has been added for loading one model at a time, please upgrade and try again. Close this if it solves your issue
